import React, { createContext, useContext, useEffect, useMemo, useState } from 'react';

const UiPreferencesContext = createContext();

const translations = {
  en: {
    'header.searchPlaceholder': 'Search recipes...',
    'header.profile': 'My profile',
    'header.logout': 'Sign out',
    'header.settings': 'Quick settings',
    'header.darkMode': 'Dark mode',
    'header.english': 'English',
    'header.settingsPage': 'Open settings',
    'header.appearance': 'Appearance',
    'header.languageShort': 'Language',
    'header.privacy': 'Privacy',
    'header.dark': 'Dark',
    'header.light': 'Light',
    'header.public': 'Public',
    'header.private': 'Private',
    'header.logoutTitle': 'Sign out',
    'header.logoutConfirm': 'Are you sure you want to sign out?',
    'common.no': 'No',
    'common.yes': 'Yes',
    'nav.home': 'Home',
    'nav.myRecipes': 'My recipes',
    'nav.recipesPersonal': 'Personal recipes',
    'nav.createRecipe': 'Create recipe',
    'nav.collections': 'Collections',
    'nav.weekPlan': 'Weekly plan',
    'nav.plates': 'Plates',
    'nav.explore': 'Explore plates',
    'nav.breakfast': 'Breakfast',
    'nav.lunch': 'Lunch',
    'nav.dinner': 'Dinner',
    'nav.other': 'Other',
    'nav.contact': 'Contact',
    'nav.settings': 'Settings',
    'nav.profile': 'My profile',
    'settings.title': 'General settings',
    'settings.subtitle': 'Control language, appearance, and interaction preferences.',
    'settings.language': 'Language',
    'settings.spanish': 'Spanish',
    'settings.english': 'English',
    'settings.appearance': 'Appearance',
    'settings.light': 'Light mode',
    'settings.dark': 'Dark mode',
    'settings.comments': 'Comments visibility',
    'settings.public': 'Public',
    'settings.private': 'Private',
    'settings.devices': 'Devices',
    'settings.connectMobile': 'Connect with your mobile account?',
    'settings.yes': 'Yes',
    'settings.no': 'No',
    'settings.save': 'Save changes',
    'settings.saved': 'Changes saved successfully',
    'settings.loading': 'Loading settings...',
    'settings.accountPrivacy': 'Account and privacy',
    'settings.usageExperience': 'Experience',
    'settings.units': 'Units',
    'settings.metric': 'Metric',
    'settings.imperial': 'Imperial',
    'settings.weeklySummary': 'Weekly summary',
    'settings.enabled': 'Enabled',
    'settings.disabled': 'Disabled',
    'settings.nutritionGoal': 'Nutrition goal',
    'settings.goalBalanced': 'Balanced',
    'settings.goalEnergy': 'More energy',
    'settings.goalDefinition': 'Definition',
    'settings.goalGain': 'Muscle gain',
    'auth.themeLight': 'Light mode',
    'auth.themeDark': 'Dark mode',
    'auth.spanish': 'Spanish',
    'auth.english': 'English',
    'login.welcomeTitle': 'Welcome to FitFood',
    'login.welcomeSubtitle': 'Your daily ally for healthier eating.',
    'login.title': 'Sign in',
    'login.user': 'Username',
    'login.password': 'Password',
    'login.submitLoading': 'Signing in...',
    'login.submit': 'Access',
    'login.noAccount': "Don't have an account yet?",
    'login.createAccount': 'Create account',
    'login.errorAuth': 'Sign-in error',
    'login.errorConnection': 'Connection error. Verify the server is running.',
    'login.visualTitle': 'Small habits, big changes',
    'login.visualText': 'Every mindful dish is a step toward your best version. Start today with FitFood.',
    'register.title': 'Create account',
    'register.subtitle': 'Access your recipes, plans, and personalized settings.',
    'register.photo': 'Profile photo',
    'register.uploadImage': 'Upload image',
    'register.personalData': 'Personal data',
    'register.firstName': 'First name',
    'register.lastName': 'Last name',
    'register.username': 'Username',
    'register.password': 'Password',
    'register.email': 'Email',
    'register.phone': 'Phone number',
    'register.notifications': 'Email notifications',
    'register.visibility': 'Visibility',
    'register.public': 'Public',
    'register.private': 'Private',
    'register.requiredNote': "*Fields with the '▶' icon are required",
    'register.placeholderLastName': 'Your last name',
    'register.placeholderUsername': 'Your username',
    'register.placeholderPassword': 'Min. 8 chars, uppercase, number, and symbol',
    'register.placeholderPhone': 'Your phone number',
    'register.submitLoading': 'Creating account...',
    'register.submit': 'Create user',
    'register.backToLogin': 'Back to login',
    'register.success': 'Account created successfully! Redirecting to login...',
    'register.errorCreate': 'Error creating account',
    'register.errorConnection': 'Connection error. Verify the server is running.',
    'contact.breadcrumb': 'Contact',
    'contact.kicker': 'FitFood support',
    'contact.title': 'Contact us',
    'contact.subtitle': 'Tell us what you need and we will help you quickly. We want your FitFood experience to be excellent.',
    'contact.highlight.response': 'Average response time',
    'contact.highlight.users': 'Users helped',
    'contact.highlight.satisfaction': 'Support satisfaction',
    'contact.messageTitle': 'Send us a message',
    'contact.messageSubtitle': 'We will reply as soon as possible.',
    'contact.fullName': 'Full name',
    'contact.subject': 'Subject',
    'contact.message': 'Message',
    'contact.placeholderName': 'Your name',
    'contact.placeholderSubject': 'How can we help you?',
    'contact.placeholderMessage': 'Write your message here...',
    'contact.sending': 'Sending...',
    'contact.send': 'Send message',
    'contact.sent': 'Message sent successfully. We will contact you soon.',
    'contact.error': 'Error sending the message. Try again.',
    'contact.otherChannelsTitle': 'You can also reach us through other channels',
    'contact.otherChannelsBody': 'Choose your preferred channel and we will contact you.',
    'contact.phone': 'Phone',
    'contact.address': 'Address',
    'contact.schedule': 'Schedule',
    'contact.faqTitle': 'Frequently asked questions',
    'contact.faq1q': 'How long do you take to reply?',
    'contact.faq1a': 'We usually reply in less than 24 business hours.',
    'contact.faq2q': 'Can I suggest new features?',
    'contact.faq2a': 'Yes, we love suggestions to improve FitFood.',
    'contact.faq3q': 'What should I include in an incident report?',
    'contact.faq3a': 'Describe the issue and, if possible, add steps to reproduce it.',
    'contact.cityCountry': '28001 Madrid, Spain',
    'contact.weekSchedule': 'Monday - Friday: 9:00 - 18:00',
    'contact.saturdaySchedule': 'Saturday: 10:00 - 14:00',
    'collections.kicker': 'New sections',
    'collections.title': 'FitFood collections',
    'collections.subtitle': 'Discover recipe groups designed for real routine goals.',
    'collections.breadcrumb1': 'My recipes',
    'collections.breadcrumb2': 'Collections',
    'collections.card1.title': 'Express breakfasts',
    'collections.card1.desc': 'Quick recipes to start your day without complications.',
    'collections.card1.action': 'View breakfasts',
    'collections.card2.title': 'Weekly batch cooking',
    'collections.card2.desc': 'Dishes to cook once and organize all week.',
    'collections.card2.action': 'Plan menu',
    'collections.card3.title': 'High-protein meals',
    'collections.card3.desc': 'Complete options to train and recover better.',
    'collections.card3.action': 'Explore dishes',
    'collections.card4.title': 'Healthy desserts',
    'collections.card4.desc': 'Light sweets with great flavor for any moment.',
    'collections.card4.action': 'See other dishes',
    'plan.breadcrumb1': 'My recipes',
    'plan.breadcrumb2': 'Weekly plan',
    'plan.kicker': 'Planning',
    'plan.title': 'Suggested weekly plan',
    'plan.subtitle': 'A base proposal to organize your meals. You can use it as a starting point.',
    'plan.viewIdeas': 'View ideas',
    'explorer.breadcrumb1': 'Dishes',
    'explorer.breadcrumb2': 'Explore',
    'explorer.title': 'Explore dishes',
    'explorer.subtitle': 'Choose a category and discover recipes for every moment of the day.',
    'explorer.openCategory': 'Open category',
    'explorer.breakfastSubtitle': 'Start your day with energy',
    'explorer.lunchSubtitle': 'Complete and balanced dishes',
    'explorer.dinnerSubtitle': 'Light and tasty options',
    'explorer.otherSubtitle': 'Snacks, desserts, and more ideas',
    'breakfast.breadcrumb1': 'Dishes',
    'breakfast.quickExplore': 'Explore',
    'breakfast.quickBreakfast': 'Breakfast',
    'breakfast.quickLunch': 'Lunch',
    'breakfast.quickDinner': 'Dinner',
    'breakfast.quickOther': 'Other',
    'breakfast.loading': 'Loading recipes...',
    'breakfast.errorTitle': 'Error loading recipes',
    'breakfast.errorBody': 'Recipes could not be loaded. Please try again.',
    'breakfast.retry': 'Retry',
    'breakfast.emptyTitle': 'No recipes available',
    'breakfast.emptyBody': 'There are no recipes in this category yet. Be the first to create one!',
    'breakfast.createFirst': 'Create {category} recipe',
    'breakfast.recommendation': 'Today recommendation',
    'breakfast.viewRecommendation': 'View recommendation',
    'breakfast.noDescription': 'An ideal recipe to keep your healthy routine with great flavor.',
    'breakfast.noImage': 'No image',
    'breakfast.noShortDescription': 'No description',
    'breakfast.medium': 'Medium',
    'breakfast.viewRecipe': 'View recipe',
    'footer.recipeLibrary': 'Recipe library',
    'footer.cookiesConfig': 'Cookie settings',
    'footer.company': 'Our company',
    'footer.press': 'Press',
    'footer.collaborate': 'Work with us',
    'footer.partners': 'Partners',
    'footer.affiliates': 'Affiliates',
    'footer.terms': 'Terms and conditions',
    'footer.privacy': 'Privacy policy',
    'footer.cookies': 'Cookie policy',
    'footer.accessibility': 'Accessibility statement',
    'home.slide.defaultDesc': 'Discover a healthy recipe created by the FitFood community.',
    'home.slide.defaultTag': 'FitFood recipe',
    'home.featured.kicker': 'Inspiration of the week',
    'home.featured.title': 'Featured recipes',
    'home.featured.description': 'Discover healthy recipes with a visual style integrated into FitFood.',
    'home.carousel.prev': 'Previous',
    'home.carousel.next': 'Next',
    'home.carousel.nav': 'Carousel navigation',
    'home.carousel.goTo': 'Go to',
    'home.recent.title': 'Recently created recipes',
    'home.recent.myRecipes': 'View my recipes',
    'home.recent.name': 'Name',
    'home.recent.description': 'Description',
    'home.recent.calories': 'Calories',
    'home.recent.difficulty': 'Difficulty',
    'home.recent.date': 'Creation date',
    'home.recent.viewCategory': 'View category',
    'home.fallback.breakfast': 'View breakfasts',
    'home.fallback.discover': 'Discover ideas',
    'home.fallback.meals': 'View meals',
    'home.fallback.dinners': 'Explore dinners',
    'home.fallback.more': 'View more recipes',
    'home.hero.title': 'Welcome to FitFood',
    'home.hero.subtitle': 'Your daily ally for healthier eating.',
    'home.hero.body1': 'FitFood helps you keep track of your meals in a simple and clear way.',
    'home.hero.body2': 'Track dishes, estimate calories automatically, and follow your progress in real time.',
    'home.hero.body3': 'Create personalized plans and share healthy recipes with the community.',
    'assistant.welcome': 'Hi, I am your FitFood assistant. How can I help you today?',
    'assistant.errorLoginRequired': 'You need to sign in to use the assistant.',
    'assistant.errorNoResponse': 'Could not get a response from AI.',
    'assistant.errorConnect': 'Could not connect to AI.',
    'assistant.openAria': 'Open AI assistant',
    'assistant.title': 'FitFood Assistant',
    'assistant.subtitle': 'Powered by Qwen3 (LM Studio)',
    'assistant.thinking': 'Thinking...',
    'assistant.placeholder': 'Write your question...',
    'assistant.send': 'Send',
    'assistant.promptBreakfast': 'Suggest a quick and healthy breakfast.',
    'assistant.promptMacros': 'How can I balance proteins, fats, and carbs?',
    'assistant.promptDinner': 'Give me ideas for a light dinner.',
    'assistant.hintBreakfast': 'Quick breakfast',
    'assistant.hintMacros': 'Macros',
    'assistant.hintDinner': 'Light dinner',
    'myRecipes.confirmDelete': 'Are you sure you want to delete this recipe?',
    'myRecipes.deleteError': 'Error deleting recipe',
    'myRecipes.loading': 'Loading your recipes...',
    'myRecipes.errorTitle': 'Error loading recipes',
    'myRecipes.errorBody': 'Your recipes could not be loaded. Please try again.',
    'myRecipes.retry': 'Retry',
    'myRecipes.emptyTitle': "You don't have recipes yet",
    'myRecipes.emptyBody': 'Start by creating your first healthy recipe',
    'myRecipes.createFirst': 'Create my first recipe',
    'myRecipes.title': 'MY RECIPES',
    'myRecipes.subtitle': 'Here you can view your created recipes',
    'myRecipes.summaryTotal': 'Total recipes',
    'myRecipes.summaryCalories': 'Average calories',
    'myRecipes.summaryLatest': 'Latest creation',
    'createRecipe.breadcrumb': 'Create New Recipe',
    'createRecipe.errorImageUpload': 'Error uploading image',
    'createRecipe.errorImageProcess': 'Error processing image',
    'createRecipe.errorLogin': 'You must sign in',
    'createRecipe.errorNameRequired': 'Recipe name is required',
    'createRecipe.errorIngredients': 'Add at least one valid ingredient from the list',
    'createRecipe.success': 'Recipe created successfully',
    'createRecipe.errorCreate': 'Error creating recipe',
    'createRecipe.subtitle': 'Here you can create your own recipe, add an image of the result, include the ingredients list, and much more...',
    'createRecipe.dataTitle': 'DATA',
    'createRecipe.previewAlt': 'Preview',
    'createRecipe.uploading': 'Uploading image...',
    'createRecipe.uploadFromDevice': 'Upload from device',
    'createRecipe.dishName': 'Dish name',
    'common.write': 'Write...',
    'createRecipe.easy': 'Easy',
    'createRecipe.medium': 'Medium',
    'createRecipe.hard': 'Hard',
    'createRecipe.category': 'Category',
    'createRecipe.snackTime': 'Snack time',
    'createRecipe.snack': 'Snack',
    'createRecipe.dessert': 'Dessert',
    'createRecipe.drink': 'Drink',
    'createRecipe.prepTime': 'Preparation time (minutes)',
    'createRecipe.ingredientsTitle': 'INGREDIENTS',
    'createRecipe.ingredientsHint': 'Type at least 3 letters to search ingredients in the database',
    'createRecipe.ingredientPlaceholder': 'Type the food name',
    'createRecipe.detailedDescription': 'DETAILED DESCRIPTION',
    'createRecipe.stepsPlaceholder': 'Write preparation steps and other details...',
    'common.saving': 'Saving...',
    'common.accept': 'Accept',
    'common.clearFields': 'Clear fields',
    'common.delete': 'Delete',
    'recipeDetail.breadcrumb': 'Recipe Detail',
    'recipeDetail.notFound': 'Recipe not found',
    'recipeDetail.loadError': 'Error loading recipe',
    'recipeDetail.favoriteError': 'Error updating favorite',
    'recipeDetail.selectRating': 'Select a rating',
    'recipeDetail.ratingSent': 'Rating sent',
    'recipeDetail.ratingError': 'Error sending rating',
    'recipeDetail.loading': 'Loading recipe...',
    'recipeDetail.backToRecipes': 'Back to recipes',
    'recipeDetail.inFavorites': 'In favorites',
    'recipeDetail.addFavorite': 'Add to favorites',
    'recipeDetail.anonymous': 'Anonymous',
    'recipeDetail.general': 'General',
    'recipeDetail.nutrition': 'Nutrition facts',
    'recipeDetail.proteins': 'Proteins',
    'recipeDetail.carbs': 'Carbs',
    'recipeDetail.fats': 'Fats',
    'recipeDetail.ingredient': 'Ingredient',
    'recipeDetail.noIngredients': 'No ingredients available',
    'recipeDetail.preparation': 'Preparation',
    'recipeDetail.noInstructions': 'No instructions available',
    'recipeDetail.rateTitle': 'Rate this recipe',
    'recipeDetail.commentPlaceholder': 'Write a comment (optional)',
    'recipeDetail.sendRating': 'Send rating',
    'profile.invalidSession': 'Invalid session. Please sign in again.',
    'profile.loadError': 'Error loading profile',
    'profile.imageSizeError': 'Image cannot exceed 5MB',
    'profile.passwordMismatch': 'Passwords do not match',
    'profile.currentPasswordRequired': 'You must enter your current password to change it',
    'profile.passwordLengthError': 'New password must be at least 8 characters',
    'profile.updateError': 'Error updating profile',
    'profile.updated': 'Profile updated successfully',
    'profile.loading': 'Loading profile...',
    'profile.changeImage': 'Change image',
    'profile.kicker': 'FitFood profile',
    'profile.subtitle': 'Keep your data up to date to better personalize recipes and recommendations.',
    'profile.personalData': 'Personal data',
    'profile.optional': 'Optional',
    'profile.notifications': 'Notifications',
    'profile.securityTitle': 'Account security',
    'profile.securityNote': 'Fill these fields only if you want to change your password.',
    'profile.currentPassword': 'Current password',
    'profile.currentPasswordPlaceholder': 'Required if you change password',
    'profile.newPassword': 'New password',
    'profile.newPasswordPlaceholder': 'Minimum 8 characters',
    'profile.confirmPassword': 'Confirm password',
    'profile.confirmPasswordPlaceholder': 'Repeat new password',
    'profile.saveChanges': 'Save changes',
    'forbidden.subtitle': 'Access denied',
    'forbidden.title': 'You do not have permissions',
    'forbidden.description': 'You are not authorized to access this page',
    'forbidden.back': 'Go back',
    'forbidden.home': 'Go to home',
    'notFound.subtitle': 'Oops... it looks like there was a problem',
    'notFound.title': 'Page not found',
    'notFound.description': 'The page you are trying to open is unavailable or has been moved.',
    'notFound.back': 'Go back',
    'notFound.backHome': 'Back to home',
    'notFound.report': 'Report that this page is not working'
  }
};

const defaultSettings = {
  language: 'es',
  theme: 'light'
};

export const UiPreferencesProvider = ({ children }) => {
  const [preferences, setPreferences] = useState(defaultSettings);

  useEffect(() => {
    const saved = localStorage.getItem('uiPreferences');
    if (saved) {
      try {
        const parsed = JSON.parse(saved);
        setPreferences((prev) => ({ ...prev, ...parsed }));
      } catch {
        setPreferences(defaultSettings);
      }
    }
  }, []);

  useEffect(() => {
    localStorage.setItem('uiPreferences', JSON.stringify(preferences));

    if (preferences.theme === 'dark') {
      document.body.classList.add('theme-dark');
    } else {
      document.body.classList.remove('theme-dark');
    }

    document.documentElement.setAttribute('lang', preferences.language === 'en' ? 'en' : 'es');
  }, [preferences]);

  const setTheme = (theme) => {
    setPreferences((prev) => ({ ...prev, theme }));
  };

  const toggleTheme = () => {
    setPreferences((prev) => ({ ...prev, theme: prev.theme === 'dark' ? 'light' : 'dark' }));
  };

  const setLanguage = (language) => {
    setPreferences((prev) => ({ ...prev, language }));
  };

  const toggleLanguage = () => {
    setPreferences((prev) => ({ ...prev, language: prev.language === 'es' ? 'en' : 'es' }));
  };

  const t = (key, fallback = '') => {
    if (preferences.language !== 'en') {
      return fallback || key;
    }
    return translations.en[key] || fallback || key;
  };

  const value = useMemo(
    () => ({
      preferences,
      setTheme,
      toggleTheme,
      setLanguage,
      toggleLanguage,
      t
    }),
    [preferences]
  );

  return <UiPreferencesContext.Provider value={value}>{children}</UiPreferencesContext.Provider>;
};

export const useUiPreferences = () => {
  const context = useContext(UiPreferencesContext);
  if (!context) {
    throw new Error('useUiPreferences debe usarse dentro de UiPreferencesProvider');
  }
  return context;
};
